<?xml version="1.0"?>
<robot name="eod" xmlns:xacro="http://www.ros.org/wiki/xacro">
  

  <xacro:include filename="$(find eod_pkg)/description/wheel.urdf.xacro" /> 


<!-- Defining the colors used in this robot -->
  <material name="Black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="Red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <material name="White">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>


  <material name="Blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>



  <!-- PROPERTY LIST -->
  <!--All units in m-kg-s-radians unit system -->
  <property name="M_PI" value="3.1415926535897931" />
  <property name="M_PI_2" value="1.570796327" />
  <property name="DEG_TO_RAD" value="0.017453293" />

  <!-- Main body radius and height -->
  <!-- Main Body Cylinder base   -->
  <property name="base_height" value="0.04" /> 
  <property name="base_width" value="0.10" />
  <property name="base_length" value="0.15" /> 

  <!-- Kinect dimensions   -->
  <property name="kinect_height" value="0.04" /> 
  <property name="kinect_width" value="0.10" />
  <property name="kinect_length" value="0.15" /> 

  
  <!-- caster wheel radius and height -->
  <property name="caster_height" value="0.04" /> 
  <property name="caster_radius" value="0.025" /> 
  

  <!-- Wheels -->
  <property name="base_x_origin_to_wheel_origin" value="0.25" />
  <property name="base_y_origin_to_wheel_origin" value="0.3" />
  <property name="base_z_origin_to_wheel_origin" value="0.0" />


  <!-- BASE-FOOTPRINT -->
  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->
  <link name="base_footprint">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius - base_z_origin_to_wheel_origin}" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>
  

  <!-- BASE-LINK -->
  <!--Actual body/chassis of the robot-->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
          <box size="${base_length},{base_height},{base_width}" />
      </geometry>
      <material name="White" />
    </visual>   
  </link>


<!--Caster -->

  <link name="caster_link">

    <visual>
      <origin xyz="0 0.02 0" rpy="${M_PI/2} 0 0" />
      <geometry>
	       <sphere radius="${caster_radius}" />
      </geometry>
      <material name="Black" />
    </visual>  
    <collision>
      <geometry>

	     <sphere radius="${caster_radius}" />
      
      </geometry>
      <origin xyz="0 0.02 0" rpy="${M_PI/2} 0 0" />
    </collision>      
  </link>



 <joint name="caster_joint" type="fixed">
      <parent link="base_link"/>
      <child link="caster_front_link"/>
      <origin xyz="0.07 0.0 0.007" rpy="${-M_PI/2} 0 0"/>
</joint>
    

<!-- Wheel Definitions -->

  <wheel  lr="right" parent="base_link" translateX="0" translateY="0.2" flipY="1"/>
  <wheel  lr="left" parent="base_link" translateX="0" translateY="-0.2" flipY="1"/>
	 
  
  <!-- SENSORS -->
  
  <!-- Kinect -->

  <link name="kinect_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${hokuyo_size} ${hokuyo_size} ${hokuyo_size}"/>
      </geometry>
      <material name="Blue" />
    </visual>
  </link>
  
  <joint name="hokuyo_joint" type="fixed">
    <origin xyz="${base_radius - hokuyo_size/2} 0 ${base_height+hokuyo_size/4}" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="hokuyo_link" />
  </joint>

</robot>
