<?xml version="1.0"?>
<robot name="eod" xmlns:xacro="http://www.ros.org/wiki/xacro">
  

  <xacro:include filename="$(find eod_pkg)/description/wheel.urdf.xacro" /> 


<!-- Defining the colors used in this robot -->
  <material name="Black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="Red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <material name="White">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>


  <material name="Blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>



  <!-- PROPERTY LIST -->
  <!--All units in m-kg-s-radians unit system -->
  <property name="M_PI" value="3.1415926535897931" />
  <property name="M_PI_2" value="1.570796327" />
  <property name="DEG_TO_RAD" value="0.017453293" />

  <!-- Main body radius and height -->
  <!-- Main Body Cylinder base   -->
  <property name="base_height" value="0.033" /> 
  <property name="base_width" value="0.10" />
  <property name="base_length" value="0.212" />
  <property name="back_base_offset" value="0.08" />
  <property name="height_from_floor" value="0.045" />
  
  <!-- distanza tra i centri delle due ruote -->
  <property name="l" value="0.135" /> 
  <!-- distanza tra l'altezza del centro delle ruote (raggio) e la superfice
  inferiore della base -->
  <property name="r_base_offset" value="0.012" /> 

  <!-- Tower dimensions   -->
  <property name="tower_height" value="0.225" /> 
  <property name="tower_width" value="0.072" />
  <property name="tower_length" value="0.027" />

  <!-- wheel radius and height -->
  <property name="wheel_radius" value="0.033" /> 
  <property name="wheel_height" value="0.021" />
  <property name="wheel_to_front" value="0.08" />
  <property name="wheel_to_back" value="0.132" />
  

  
  <!-- caster wheel radius and height -->
  <property name="caster_height" value="0.04" /> 
  <property name="caster_radius" value="0.011" /> 
  <property name="caster_base_offset" value="0.115" /> 
  <property name="caster_to_back" value="0.017" /> 


  <!-- Kinect dimensions   -->
  <property name="kinect_height" value="0.07" /> 
  <property name="kinect_width" value="0.28" />
  <property name="kinect_length" value="0.07" /> 
  <!-- presunta altezza del sistema di riferimento della kinect -->
  <property name="kinect_focus_height" value="0.053" /> 

  
  <!-- Wheels -->
  <!--property name="base_x_origin_to_wheel_origin" value="0.25" />
  <property name="base_y_origin_to_wheel_origin" value="0.3" />
  <property name="base_z_origin_to_wheel_origin" value="0.0" /-->


  <!-- BASE-FOOTPRINT -->
  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->
  <link name="base_footprint">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>
  

  <!-- BASE-LINK -->
  <!--Actual body/chassis of the robot-->
  <link name="base_link">
    <visual>
      <origin xyz="${-(base_length/2-back_base_offset)} 0 ${base_height/2+r_base_offset}" rpy="0 0 0" />
      <geometry>
          <box size="${base_length} ${base_width} ${base_height} " />
      </geometry>
      <material name="White" />
    </visual>   
  </link>

 
 <!-- TOWER-LINK -->
  <link name="tower_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
          <box size=" ${tower_length} ${tower_width} ${tower_height} " />
      </geometry>
      <material name="White" />
    </visual>   
  </link>

  <joint name="tower_joint" type="fixed">
    <parent link="base_link"/>
    <child link="tower_link"/>
    <origin xyz="${-wheel_to_back+tower_length/2.0} 0.0 ${r_base_offset+base_height+tower_height/2}" rpy="0 0 0"/>
  </joint>

<!--Caster -->

  <link name="caster_link">

    <visual>
      <origin xyz="0 0 ${-r_base_offset}" rpy="0 0 0" />
      <geometry>
	       <sphere radius="${height_from_floor/2.0}" />
      </geometry>
      <material name="Black" />
    </visual>     
  </link>



 <joint name="caster_joint" type="fixed">
      <parent link="base_link"/>
      <child link="caster_link"/>
      <origin xyz="${-caster_base_offset} 0.0 0" rpy="0 0 0"/>
</joint>
    

<!-- Wheel Definitions -->
  <wheel  lr="right" parent="base_link" translateX="0" translateY="0.2" flipY="1"/>
  <wheel  lr="left" parent="base_link" translateX="0" translateY="-0.2" flipY="1"/>
	 
  
  <!-- SENSORS -->
  
  <!-- Kinect -->
  <link name="kinect_link">
    <visual>
      <origin xyz="0 0 ${-(kinect_height-kinect_focus_height)}" rpy="0 0 0" />
      <geometry>
        <box size="${kinect_length} ${kinect_width} ${kinect_height}"/>
      </geometry>
      <material name="Blue" />
    </visual>
  </link>
  
  <joint name="kinect_joint" type="fixed">
    <origin xyz="0 0 ${tower_height/2 + kinect_focus_height}" rpy="0 0 0" />
    <parent link="tower_link"/>
    <child link="kinect_link" />
  </joint>

</robot>
