<?xml version="1.0"?>
<robot name="sensor_kinect" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="/opt/ros/kinetic/share/turtlebot_description/urdf/turtlebot_gazebo.urdf.xacro"/>
  <xacro:include filename="/opt/ros/kinetic/share/turtlebot_description/urdf/turtlebot_properties.urdf.xacro"/>
  
  <property name="PI" value="3.1415926535897931" />

  <xacro:property name="kinect_cam_py" value="-0.0125"/>
  <property name="kinect_base_height" value="0.035"/>
  <property name="tower_height" value="0.225" /> 
  <property name="tower_length" value="0.027" />
  
  <!-- piccola quantita' per far andare la kinect inclinata sulla torretta-->
  <property name="bias" value="0.003" />

  <!-- Parameterised in part by the values in turtlebot_properties.urdf.xacro -->
  <xacro:macro name="sensor_kinect" params="parent">
      
    <joint name="camera_joint" type="fixed">
      <origin xyz="${tower_length} 0 ${ tower_height/2 + kinect_base_height }" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child link="camera_link"/>
    </joint>  
    

    <joint name="camera_rgb_joint" type="fixed">
      <origin xyz="0.031 ${kinect_cam_py} 0.016" rpy="${cam_or} ${cam_op} ${cam_oy}"/>
      <parent link="camera_link"/>
      <child link="camera_rgb_frame" />
    </joint>
    <link name="camera_rgb_frame"/>

    <joint name="camera_rgb_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="camera_rgb_frame" />
      <child link="camera_rgb_optical_frame" />
    </joint>
    <link name="camera_rgb_optical_frame"/>

     

    <link name="camera_link">
      <visual>
       <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}"/>
        <geometry>
         <mesh filename="package://turtlebot_description/meshes/sensors/kinect.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
        <geometry>
          <box size="0.07271 0.27794 0.073"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.564" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0"
                 iyy="0.000498940" iyz="0.0"
                 izz="0.003879257" />
      </inertial>
    </link>

  </xacro:macro>
</robot>
